 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/aseguradoras", type: :request do
  # Aseguradora. As you add validations to Aseguradora, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Aseguradora.create! valid_attributes
      get aseguradoras_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      aseguradora = Aseguradora.create! valid_attributes
      get aseguradora_url(aseguradora)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_aseguradora_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      aseguradora = Aseguradora.create! valid_attributes
      get edit_aseguradora_url(aseguradora)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Aseguradora" do
        expect {
          post aseguradoras_url, params: { aseguradora: valid_attributes }
        }.to change(Aseguradora, :count).by(1)
      end

      it "redirects to the created aseguradora" do
        post aseguradoras_url, params: { aseguradora: valid_attributes }
        expect(response).to redirect_to(aseguradora_url(Aseguradora.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Aseguradora" do
        expect {
          post aseguradoras_url, params: { aseguradora: invalid_attributes }
        }.to change(Aseguradora, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post aseguradoras_url, params: { aseguradora: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested aseguradora" do
        aseguradora = Aseguradora.create! valid_attributes
        patch aseguradora_url(aseguradora), params: { aseguradora: new_attributes }
        aseguradora.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the aseguradora" do
        aseguradora = Aseguradora.create! valid_attributes
        patch aseguradora_url(aseguradora), params: { aseguradora: new_attributes }
        aseguradora.reload
        expect(response).to redirect_to(aseguradora_url(aseguradora))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        aseguradora = Aseguradora.create! valid_attributes
        patch aseguradora_url(aseguradora), params: { aseguradora: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested aseguradora" do
      aseguradora = Aseguradora.create! valid_attributes
      expect {
        delete aseguradora_url(aseguradora)
      }.to change(Aseguradora, :count).by(-1)
    end

    it "redirects to the aseguradoras list" do
      aseguradora = Aseguradora.create! valid_attributes
      delete aseguradora_url(aseguradora)
      expect(response).to redirect_to(aseguradoras_url)
    end
  end
end
