 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/beneficios", type: :request do
  # Beneficio. As you add validations to Beneficio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Beneficio.create! valid_attributes
      get beneficios_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      beneficio = Beneficio.create! valid_attributes
      get beneficio_url(beneficio)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_beneficio_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      beneficio = Beneficio.create! valid_attributes
      get edit_beneficio_url(beneficio)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Beneficio" do
        expect {
          post beneficios_url, params: { beneficio: valid_attributes }
        }.to change(Beneficio, :count).by(1)
      end

      it "redirects to the created beneficio" do
        post beneficios_url, params: { beneficio: valid_attributes }
        expect(response).to redirect_to(beneficio_url(Beneficio.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Beneficio" do
        expect {
          post beneficios_url, params: { beneficio: invalid_attributes }
        }.to change(Beneficio, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post beneficios_url, params: { beneficio: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested beneficio" do
        beneficio = Beneficio.create! valid_attributes
        patch beneficio_url(beneficio), params: { beneficio: new_attributes }
        beneficio.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the beneficio" do
        beneficio = Beneficio.create! valid_attributes
        patch beneficio_url(beneficio), params: { beneficio: new_attributes }
        beneficio.reload
        expect(response).to redirect_to(beneficio_url(beneficio))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        beneficio = Beneficio.create! valid_attributes
        patch beneficio_url(beneficio), params: { beneficio: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested beneficio" do
      beneficio = Beneficio.create! valid_attributes
      expect {
        delete beneficio_url(beneficio)
      }.to change(Beneficio, :count).by(-1)
    end

    it "redirects to the beneficios list" do
      beneficio = Beneficio.create! valid_attributes
      delete beneficio_url(beneficio)
      expect(response).to redirect_to(beneficios_url)
    end
  end
end
