 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/organizacoes", type: :request do
  # Organizacao. As you add validations to Organizacao, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Organizacao.create! valid_attributes
      get organizacoes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      organizacao = Organizacao.create! valid_attributes
      get organizacao_url(organizacao)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_organizacao_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      organizacao = Organizacao.create! valid_attributes
      get edit_organizacao_url(organizacao)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Organizacao" do
        expect {
          post organizacoes_url, params: { organizacao: valid_attributes }
        }.to change(Organizacao, :count).by(1)
      end

      it "redirects to the created organizacao" do
        post organizacoes_url, params: { organizacao: valid_attributes }
        expect(response).to redirect_to(organizacao_url(Organizacao.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Organizacao" do
        expect {
          post organizacoes_url, params: { organizacao: invalid_attributes }
        }.to change(Organizacao, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post organizacoes_url, params: { organizacao: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested organizacao" do
        organizacao = Organizacao.create! valid_attributes
        patch organizacao_url(organizacao), params: { organizacao: new_attributes }
        organizacao.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the organizacao" do
        organizacao = Organizacao.create! valid_attributes
        patch organizacao_url(organizacao), params: { organizacao: new_attributes }
        organizacao.reload
        expect(response).to redirect_to(organizacao_url(organizacao))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        organizacao = Organizacao.create! valid_attributes
        patch organizacao_url(organizacao), params: { organizacao: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested organizacao" do
      organizacao = Organizacao.create! valid_attributes
      expect {
        delete organizacao_url(organizacao)
      }.to change(Organizacao, :count).by(-1)
    end

    it "redirects to the organizacoes list" do
      organizacao = Organizacao.create! valid_attributes
      delete organizacao_url(organizacao)
      expect(response).to redirect_to(organizacoes_url)
    end
  end
end
