 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/seguradoras", type: :request do
  # Seguradora. As you add validations to Seguradora, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Seguradora.create! valid_attributes
      get seguradoras_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      seguradora = Seguradora.create! valid_attributes
      get seguradora_url(seguradora)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_seguradora_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      seguradora = Seguradora.create! valid_attributes
      get edit_seguradora_url(seguradora)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Seguradora" do
        expect {
          post seguradoras_url, params: { seguradora: valid_attributes }
        }.to change(Seguradora, :count).by(1)
      end

      it "redirects to the created seguradora" do
        post seguradoras_url, params: { seguradora: valid_attributes }
        expect(response).to redirect_to(seguradora_url(Seguradora.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Seguradora" do
        expect {
          post seguradoras_url, params: { seguradora: invalid_attributes }
        }.to change(Seguradora, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post seguradoras_url, params: { seguradora: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested seguradora" do
        seguradora = Seguradora.create! valid_attributes
        patch seguradora_url(seguradora), params: { seguradora: new_attributes }
        seguradora.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the seguradora" do
        seguradora = Seguradora.create! valid_attributes
        patch seguradora_url(seguradora), params: { seguradora: new_attributes }
        seguradora.reload
        expect(response).to redirect_to(seguradora_url(seguradora))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        seguradora = Seguradora.create! valid_attributes
        patch seguradora_url(seguradora), params: { seguradora: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested seguradora" do
      seguradora = Seguradora.create! valid_attributes
      expect {
        delete seguradora_url(seguradora)
      }.to change(Seguradora, :count).by(-1)
    end

    it "redirects to the seguradoras list" do
      seguradora = Seguradora.create! valid_attributes
      delete seguradora_url(seguradora)
      expect(response).to redirect_to(seguradoras_url)
    end
  end
end
